import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { openSans } from './fonts'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Discover Amsterdam',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${openSans.variable} font-sans`}>
        {children}
      </body>
    </html>
  )
}
